### ISSUE TITLE
To many options

### ISSUE THREAD

**Issue by qorahoja** [Abdulvoris101/Vote-bot#1]
Hi abdulwaris I tried your code and got an error in sl.py can you help me fix it

driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got multiple values for argument 'options'

**Comment by Abdulvoris101** [comment]
Hello you need to install chrome driver
